### PR TITLE
Pull Request for TSE Review of Enumerable Module Assignment

### PR DESCRIPTION
**Pull request by Calvinoea**
Hello, I am making a pull request for TSE review of my submission for completion of the enumerable assignment, as part of the Microverse Ruby curriculum.

Requirements of the assignment included the creation of an enumarable module with customized methods, made to imitate behaviour Ruby methods.

Features of the project include custom methods in an enumerable module:

- my_each
- my_each_with_index
- my_select
- my_all?
- my_any?
- my_none?
- my_count
- my_map
- my_inject
- multiply_els

The project has been made using Ruby, Stickler, Rubcop, and VSCode. These tools have been used to code the solution and to check for errors.

Thank you to the Microverse engineers for taking the time to review the project and provide feedback.

Changes made after review includes:

- My_all? returning true when a class is passed as an argument if all of the collection is a member of such a class
- My_all? returning true if all of the collection matches the pattern
- My_any? returning true when a class is passed as an argument  and at least one of the collection is a member of such class
- My_any? returning false if none of the collection matches a regex
- My_none? returning true if  a class is passed as an argument and none of the collection is a member of such class
- My_none? returning false if none of the collection matches the regex
- My_count returning the number of elements yielding a true value if a block is given
- My_count returning the number of items that are equal to the item if an argument is given

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
The project requires changes.

**Comment by pelzolga123** [comment]
## Hi Calvin!  
### You did a good job so far :+1: 
Still, there are changes required before this project can be approved:

*  #### My_all?
* [x]  When a class is passed as an argument should return true if all of the collection is a member of such class. For example:
`[3, 3, 3].my_all?(Integer)` - should return true

* [x] When a Regex is passed as an argument should return true if all of the collection matches the pattern. For example:
`['dog', 'bird','door' ].my_all?(/d/)` - should return true

*  #### My_any?
* [x] When a class is passed as an argument should return true if at least one of the collection is a member of such class. For example:
`[1, 2, 3, 4, 5].my_any?(Integer)` - should return true

* [ ]  When a Regex is passed as an argument should return false if none of the collection matches the Regex. For example:
`['dog','door','dish'].my_any?(/d/)` - should return true

*  #### My_none?
* [x] When a class is passed as an argument should return true if none of the collection is a member of such class. For example:
`['hi', 1, 2 ,3].my_none?(String)` - should return false

* [x]  When a Regex is passed as an argument should return true only if none of the collection matches the Regex. For example:
`['dog','door','dish'].my_none?(/d/)` - should return false

* #### My_count
* [x] Should count the number of elements yielding a true value if a block is given. For example:
`[6,2,2,7,3].my_count{|num| num < 4}` - should return 3

* [ ] Should count the number of items in enum that are equal to item if an argument is given. For example: 
`[6,0,0,7,3].my_count(0)` - should return 0 

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Calvinoea** [comment]
> ## Hi Calvin! 
> ### You did a good job so far 👍
> Still, there are changes required before this project can be approved:
> 
> * #### My_all?
> * [x]   When a class is passed as an argument should return true if all of the collection is a member of such class. For example:
>   `[3, 3, 3].my_all?(Integer)` - should return true
> * [x]  When a Regex is passed as an argument should return true if all of the collection matches the pattern. For example:
>   `['dog', 'bird','door' ].my_all?(/d/)` - should return true
> * #### My_any?
> * [x]  When a class is passed as an argument should return true if at least one of the collection is a member of such class. For example:
>   `[1, 2, 3, 4, 5].my_any?(Integer)` - should return true
> * [ ]   When a Regex is passed as an argument should return false if none of the collection matches the Regex. For example:
>   `['dog','door','dish'].my_any?(/d/)` - should return true
> * #### My_none?
> * [x]  When a class is passed as an argument should return true if none of the collection is a member of such class. For example:
>   `['hi', 1, 2 ,3].my_none?(String)` - should return false
> * [x]   When a Regex is passed as an argument should return true only if none of the collection matches the Regex. For example:
>   `['dog','door','dish'].my_none?(/d/)` - should return false
> * #### My_count
> * [x]  Should count the number of elements yielding a true value if a block is given. For example:
>   `[6,2,2,7,3].my_count{|num| num < 4}` - should return 3
> * [ ]  Should count the number of items in enum that are equal to item if an argument is given. For example:
>   `[6,0,0,7,3].my_count(0)` - should return 0
> 
> ### Please kindly fix the above issues and send another code review request.
> If you have any questions or need help, you can message me on slack (@ Olga Pelts). _Happy coding_

Thank you for your review, Olga. I have made the requested changes

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

**Comment by Calvinoea** [comment]
> ### Great work implementing the suggested changes 👏 👏 Congrats, the project is approved ✔️ You may merge 👍
> Keep up the good work 💪
> **_Ahmed Mahfoudh_**

Thank you Ahmed! I will now merge.

**Pull request merged**
